chore: Remove SRI due to plugin failures
The current vite + plugin version fail with:

    [plugin vite-plugin-manifest-sri]
    Error: ENOENT: no such file or directory, open '/home/runner/work/openmensa/openmensa/public/assets/dev/assets/canteen-DJRGTepM2.jpg'

Since SRI is actually not emitted in Rails, this commit drops it.